### ISSUE TITLE
Fatal error: Uncaught Requests_Exception: cURL error 7:

### ISSUE THREAD

**Issue by Faisalpb7** [razorpay/razorpay-php-testapp#17]
Why this error:
Fatal error: Uncaught Requests_Exception: cURL error 7: Failed to connect to api.razorpay.com port 443: Connection refused in /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/razorpay-php/libs/Requests-1.7.0/library/Requests/Transport/cURL.php:422 Stack trace: #0 /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/razorpay-php/libs/Requests-1.7.0/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array) #1 /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/razorpay-php/libs/Requests-1.7.0/library/Requests.php(379): Requests_Transport_cURL->request('https://api.raz...', Array, Array, Array) #2 /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/razorpay-php/src/Request.php(56): Requests::request('https://api.raz...', Array, Array, 'POST', Array) #3 /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/razorpay-php/src/Entity.php(86): Razorpay\Api\Request->request('POST', 'https://api.raz...', Array) #4 /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/r in /srv/disk2/3536898/www/hijabs.onlinewebshop.net/razorpay/razorpay-php/libs/Requests-1.7.0/library/Requests/Transport/cURL.php on line 422

**Comment by gkArvindr** [comment]
did you get a answer, i too am getting the same error
