### ISSUE TITLE
shows as The api key provided is invalid - But its valid test key

### ISSUE THREAD

**Issue by abkiran** [razorpay/razorpay-php-testapp#8]
```
Fatal error: Uncaught exception 'Razorpay\Api\Errors\BadRequestError' with message 'The api key provided is invalid' in /var/www/REPO/rtest/razorpay-php/src/Request.php:123 Stack trace: #0 /var/www/REPO/rtest/razorpay-php/src/Request.php(90): Razorpay\Api\Request->processError(Array, 401, Object(Requests_Response)) #1 /var/www/REPO/rtest/razorpay-php/src/Request.php(44): Razorpay\Api\Request->checkErrors(Object(Requests_Response)) #2 /var/www/REPO/rtest/razorpay-php/src/Entity.php(59): Razorpay\Api\Request->request('POST', 'orders/', Array) #3 /var/www/REPO/rtest/razorpay-php/src/Entity.php(15): Razorpay\Api\Entity->request('POST', 'orders/', Array) #4 /var/www/REPO/rtest/razorpay-php/src/Order.php(12): Razorpay\Api\Entity->create(Array) #5 /var/www/REPO/rtest/pay.php(24): Razorpay\Api\Order->create(Array) #6 {main} thrown in /var/www/REPO/rtest/razorpay-php/src/Request.php on line 123
```

**Comment by max1204** [comment]
I had the same issue with mine as well. I had a space in the string for keyID that being passed in API.
Make Sure you check for spaces and if the issue is still there try generating a new test credentials from your dashboard. 
$keyId= 'Sample_key';
$keySecret = 'sample_key_secret';

**Comment by captn3m0** [comment]
Thanks for the suggestion @max1204.

Marking this issue as closed.

**Comment by g-manikandan845** [comment]
I have same issue .I clear the config cache using following command .Please try this ....
   php artisan optimize:clear
It's working fine
